main: me.wilux.blockshelf_playground.BlockshelfPlayground
name: Blockshelf Playground
version: 0.1
authors: [wilux]

api-version: 1.13
depend: [Blockshelf]
load: STARTUP

commands:
  customutils:
  rpsend:
    description: debug command
    usage: /rpsend
  rpdelete:
    description: debug command
    usage: /rpdelete
  setability:
    description: debug command
    usage: /setability